# Generated by Django 6.0.4 on 2026-04-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_conditionreport_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
